// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBefYFwZxXlUE6BMOHDXF8CQpxIM-Q_HcE',
    appId: '1:595417021716:web:3a4136689a7fe15a695601',
    messagingSenderId: '595417021716',
    projectId: 'streamix-tv-app-1d979',
    authDomain: 'streamix-tv-app-1d979.firebaseapp.com',
    storageBucket: 'streamix-tv-app-1d979.firebasestorage.app',
    measurementId: 'G-LCEGPDGPG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9oApi569My47sk3Cd6TZwKA0iaqZFuaU',
    appId: '1:595417021716:android:3de13feeff4e2845695601',
    messagingSenderId: '595417021716',
    projectId: 'streamix-tv-app-1d979',
    storageBucket: 'streamix-tv-app-1d979.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiY3Bz4sDSQ17Hq8G38SbmmuDYKwl80AM',
    appId: '1:595417021716:ios:beee026fb09761de695601',
    messagingSenderId: '595417021716',
    projectId: 'streamix-tv-app-1d979',
    storageBucket: 'streamix-tv-app-1d979.firebasestorage.app',
    iosBundleId: 'com.example.stremApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiY3Bz4sDSQ17Hq8G38SbmmuDYKwl80AM',
    appId: '1:595417021716:ios:beee026fb09761de695601',
    messagingSenderId: '595417021716',
    projectId: 'streamix-tv-app-1d979',
    storageBucket: 'streamix-tv-app-1d979.firebasestorage.app',
    iosBundleId: 'com.example.stremApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBefYFwZxXlUE6BMOHDXF8CQpxIM-Q_HcE',
    appId: '1:595417021716:web:4e1e449de6872df8695601',
    messagingSenderId: '595417021716',
    projectId: 'streamix-tv-app-1d979',
    authDomain: 'streamix-tv-app-1d979.firebaseapp.com',
    storageBucket: 'streamix-tv-app-1d979.firebasestorage.app',
    measurementId: 'G-J3KEF3PXBH',
  );
}
